// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/consumer.proto

package consumer // import "github.com/995933447/bucketmq/pkg/rpc/consumer"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConsumeReq struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Subscriber           string   `protobuf:"bytes,2,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	Consumer             string   `protobuf:"bytes,3,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	RetriedCnt           uint32   `protobuf:"varint,5,opt,name=retried_cnt,json=retriedCnt,proto3" json:"retried_cnt,omitempty"`
	TimeoutMs            uint32   `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeReq) Reset()         { *m = ConsumeReq{} }
func (m *ConsumeReq) String() string { return proto.CompactTextString(m) }
func (*ConsumeReq) ProtoMessage()    {}
func (*ConsumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_4194b176a4807522, []int{0}
}
func (m *ConsumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeReq.Unmarshal(m, b)
}
func (m *ConsumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeReq.Marshal(b, m, deterministic)
}
func (dst *ConsumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeReq.Merge(dst, src)
}
func (m *ConsumeReq) XXX_Size() int {
	return xxx_messageInfo_ConsumeReq.Size(m)
}
func (m *ConsumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeReq proto.InternalMessageInfo

func (m *ConsumeReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *ConsumeReq) GetSubscriber() string {
	if m != nil {
		return m.Subscriber
	}
	return ""
}

func (m *ConsumeReq) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *ConsumeReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ConsumeReq) GetRetriedCnt() uint32 {
	if m != nil {
		return m.RetriedCnt
	}
	return 0
}

func (m *ConsumeReq) GetTimeoutMs() uint32 {
	if m != nil {
		return m.TimeoutMs
	}
	return 0
}

type ConsumeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeResp) Reset()         { *m = ConsumeResp{} }
func (m *ConsumeResp) String() string { return proto.CompactTextString(m) }
func (*ConsumeResp) ProtoMessage()    {}
func (*ConsumeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_4194b176a4807522, []int{1}
}
func (m *ConsumeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeResp.Unmarshal(m, b)
}
func (m *ConsumeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeResp.Marshal(b, m, deterministic)
}
func (dst *ConsumeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeResp.Merge(dst, src)
}
func (m *ConsumeResp) XXX_Size() int {
	return xxx_messageInfo_ConsumeResp.Size(m)
}
func (m *ConsumeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeResp proto.InternalMessageInfo

type ConnSNSrvReq struct {
	SN                   string   `protobuf:"bytes,1,opt,name=s_n,json=sN,proto3" json:"s_n,omitempty"`
	Consumer             string   `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnSNSrvReq) Reset()         { *m = ConnSNSrvReq{} }
func (m *ConnSNSrvReq) String() string { return proto.CompactTextString(m) }
func (*ConnSNSrvReq) ProtoMessage()    {}
func (*ConnSNSrvReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_4194b176a4807522, []int{2}
}
func (m *ConnSNSrvReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnSNSrvReq.Unmarshal(m, b)
}
func (m *ConnSNSrvReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnSNSrvReq.Marshal(b, m, deterministic)
}
func (dst *ConnSNSrvReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnSNSrvReq.Merge(dst, src)
}
func (m *ConnSNSrvReq) XXX_Size() int {
	return xxx_messageInfo_ConnSNSrvReq.Size(m)
}
func (m *ConnSNSrvReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnSNSrvReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnSNSrvReq proto.InternalMessageInfo

func (m *ConnSNSrvReq) GetSN() string {
	if m != nil {
		return m.SN
	}
	return ""
}

func (m *ConnSNSrvReq) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

type ConnSNSrvResp struct {
	Sn                   string   `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnSNSrvResp) Reset()         { *m = ConnSNSrvResp{} }
func (m *ConnSNSrvResp) String() string { return proto.CompactTextString(m) }
func (*ConnSNSrvResp) ProtoMessage()    {}
func (*ConnSNSrvResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_4194b176a4807522, []int{3}
}
func (m *ConnSNSrvResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnSNSrvResp.Unmarshal(m, b)
}
func (m *ConnSNSrvResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnSNSrvResp.Marshal(b, m, deterministic)
}
func (dst *ConnSNSrvResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnSNSrvResp.Merge(dst, src)
}
func (m *ConnSNSrvResp) XXX_Size() int {
	return xxx_messageInfo_ConnSNSrvResp.Size(m)
}
func (m *ConnSNSrvResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnSNSrvResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnSNSrvResp proto.InternalMessageInfo

func (m *ConnSNSrvResp) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func init() {
	proto.RegisterType((*ConsumeReq)(nil), "conumer.ConsumeReq")
	proto.RegisterType((*ConsumeResp)(nil), "conumer.ConsumeResp")
	proto.RegisterType((*ConnSNSrvReq)(nil), "conumer.ConnSNSrvReq")
	proto.RegisterType((*ConnSNSrvResp)(nil), "conumer.ConnSNSrvResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsumerClient interface {
	Consume(ctx context.Context, in *ConsumeReq, opts ...grpc.CallOption) (*ConsumeResp, error)
}

type consumerClient struct {
	cc *grpc.ClientConn
}

func NewConsumerClient(cc *grpc.ClientConn) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) Consume(ctx context.Context, in *ConsumeReq, opts ...grpc.CallOption) (*ConsumeResp, error) {
	out := new(ConsumeResp)
	err := c.cc.Invoke(ctx, "/conumer.Consumer/Consume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServer is the server API for Consumer service.
type ConsumerServer interface {
	Consume(context.Context, *ConsumeReq) (*ConsumeResp, error)
}

func RegisterConsumerServer(s *grpc.Server, srv ConsumerServer) {
	s.RegisterService(&_Consumer_serviceDesc, srv)
}

func _Consumer_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conumer.Consumer/Consume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).Consume(ctx, req.(*ConsumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Consumer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "conumer.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Consume",
			Handler:    _Consumer_Consume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/consumer.proto",
}

func init() { proto.RegisterFile("pkg/proto/consumer.proto", fileDescriptor_consumer_4194b176a4807522) }

var fileDescriptor_consumer_4194b176a4807522 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4d, 0x6f, 0x82, 0x40,
	0x14, 0x2c, 0xf8, 0xfd, 0x94, 0x36, 0xd9, 0x7a, 0xd8, 0x98, 0xb4, 0x12, 0x4e, 0x9c, 0xa0, 0x29,
	0xb6, 0x0d, 0xe9, 0x4d, 0xce, 0xf5, 0x80, 0xb7, 0x5e, 0x88, 0xac, 0x1b, 0x4b, 0x0c, 0xbb, 0xeb,
	0xee, 0xd2, 0x1f, 0xd6, 0x5f, 0xd8, 0xb0, 0x22, 0x6a, 0xbc, 0xbd, 0x99, 0xc9, 0x7b, 0x99, 0x79,
	0x03, 0x58, 0xec, 0x77, 0xa1, 0x90, 0x5c, 0xf3, 0x90, 0x70, 0xa6, 0xaa, 0x92, 0xca, 0xc0, 0x40,
	0x34, 0x20, 0x9c, 0xd5, 0xd0, 0xfb, 0xb3, 0x00, 0x92, 0xa3, 0x96, 0xd2, 0x03, 0x9a, 0x42, 0x4f,
	0x73, 0x51, 0x10, 0x6c, 0xb9, 0x96, 0x3f, 0x4a, 0x8f, 0x00, 0x3d, 0x03, 0xa8, 0x2a, 0x57, 0x44,
	0x16, 0x39, 0x95, 0xd8, 0x36, 0xd2, 0x05, 0x83, 0x66, 0x30, 0x3c, 0xdd, 0xc7, 0x1d, 0xa3, 0xb6,
	0x18, 0x21, 0xe8, 0x6e, 0x37, 0x7a, 0x83, 0xbb, 0xae, 0xe5, 0x4f, 0x52, 0x33, 0xa3, 0x39, 0x8c,
	0x25, 0xd5, 0xb2, 0xa0, 0xdb, 0x8c, 0x30, 0x8d, 0x7b, 0xae, 0xe5, 0x3b, 0x29, 0x34, 0x54, 0xc2,
	0x34, 0x7a, 0x02, 0xd0, 0x45, 0x49, 0x79, 0xa5, 0xb3, 0x52, 0xe1, 0xbe, 0xd1, 0x47, 0x0d, 0xf3,
	0xa5, 0x3c, 0x07, 0xc6, 0xad, 0x67, 0x25, 0xbc, 0x4f, 0x98, 0x24, 0x9c, 0xb1, 0xf5, 0x6a, 0x2d,
	0x7f, 0xeb, 0x10, 0x0f, 0xd0, 0x51, 0x19, 0x6b, 0x22, 0xd8, 0x6a, 0x75, 0xe5, 0xcf, 0xbe, 0xf6,
	0xe7, 0xcd, 0xc1, 0xb9, 0x58, 0x56, 0x02, 0xdd, 0x83, 0xad, 0xce, 0xcb, 0xec, 0x75, 0x09, 0xc3,
	0xe4, 0x14, 0xe6, 0x1d, 0x06, 0xcd, 0x8c, 0x1e, 0x83, 0xe6, 0x85, 0xc1, 0xf9, 0x7d, 0xb3, 0xe9,
	0x2d, 0xa9, 0x84, 0x77, 0xb7, 0x7c, 0xf9, 0x0e, 0x76, 0x85, 0xfe, 0xa9, 0xf2, 0x80, 0xf0, 0x32,
	0x8c, 0xe3, 0xb7, 0x38, 0x8a, 0x16, 0x8b, 0x8f, 0x30, 0xaf, 0xc8, 0x9e, 0xea, 0xf2, 0x10, 0xd6,
	0x45, 0x49, 0x41, 0xda, 0x9a, 0xf2, 0xbe, 0xe9, 0x29, 0xfa, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x85,
	0x61, 0x1a, 0xc1, 0xc3, 0x01, 0x00, 0x00,
}
