// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/health.proto

package health // import "github.com/995933447/bucketmq/pkg/api/health"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_health_ed0e30bf4b774b71, []int{0}
}
func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (dst *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(dst, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

type PingResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResp) Reset()         { *m = PingResp{} }
func (m *PingResp) String() string { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()    {}
func (*PingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_health_ed0e30bf4b774b71, []int{1}
}
func (m *PingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResp.Unmarshal(m, b)
}
func (m *PingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResp.Marshal(b, m, deterministic)
}
func (dst *PingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResp.Merge(dst, src)
}
func (m *PingResp) XXX_Size() int {
	return xxx_messageInfo_PingResp.Size(m)
}
func (m *PingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingReq)(nil), "api.PingReq")
	proto.RegisterType((*PingResp)(nil), "api.PingResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HealthReporterClient is the client API for HealthReporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthReporterClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
}

type healthReporterClient struct {
	cc *grpc.ClientConn
}

func NewHealthReporterClient(cc *grpc.ClientConn) HealthReporterClient {
	return &healthReporterClient{cc}
}

func (c *healthReporterClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	out := new(PingResp)
	err := c.cc.Invoke(ctx, "/api.HealthReporter/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthReporterServer is the server API for HealthReporter service.
type HealthReporterServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
}

func RegisterHealthReporterServer(s *grpc.Server, srv HealthReporterServer) {
	s.RegisterService(&_HealthReporter_serviceDesc, srv)
}

func _HealthReporter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthReporterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HealthReporter/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthReporterServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HealthReporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HealthReporter",
	HandlerType: (*HealthReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _HealthReporter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/health.proto",
}

func init() { proto.RegisterFile("pkg/proto/health.proto", fileDescriptor_health_ed0e30bf4b774b71) }

var fileDescriptor_health_ed0e30bf4b774b71 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xc8, 0x4e, 0xd7,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x48, 0x4d, 0xcc, 0x29, 0xc9, 0xd0, 0x03, 0x73, 0x84,
	0x98, 0x13, 0x0b, 0x32, 0x95, 0x38, 0xb9, 0xd8, 0x03, 0x32, 0xf3, 0xd2, 0x83, 0x52, 0x0b, 0x95,
	0xb8, 0xb8, 0x38, 0x20, 0xcc, 0xe2, 0x02, 0x23, 0x73, 0x2e, 0x3e, 0x0f, 0xb0, 0xda, 0xa0, 0xd4,
	0x82, 0xfc, 0xa2, 0x92, 0xd4, 0x22, 0x21, 0x55, 0x2e, 0x16, 0x90, 0xac, 0x10, 0x8f, 0x5e, 0x62,
	0x41, 0xa6, 0x1e, 0x54, 0x8f, 0x14, 0x2f, 0x12, 0xaf, 0xb8, 0x40, 0x89, 0xc1, 0x49, 0x2f, 0x4a,
	0x27, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xdf, 0xd2, 0xd2, 0xd4, 0xd2,
	0xd8, 0xd8, 0xc4, 0xc4, 0x5c, 0x3f, 0xa9, 0x34, 0x39, 0x3b, 0xb5, 0x24, 0xb7, 0x50, 0x1f, 0xe4,
	0x98, 0xc4, 0x82, 0x4c, 0xa8, 0x53, 0x92, 0xd8, 0xc0, 0x6e, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x78, 0xa9, 0xd6, 0xbf, 0xa5, 0x00, 0x00, 0x00,
}
