// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/ha.proto

package ha // import "github.com/995933447/bucketmq/pkg/rpc/ha"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgFileType int32

const (
	MsgFileType_MsgFileTypeNil      MsgFileType = 0
	MsgFileType_MsgFileTypeIdx      MsgFileType = 1
	MsgFileType_MsgFileTypeData     MsgFileType = 2
	MsgFileType_MsgFileTypeFinish   MsgFileType = 3
	MsgFileType_MsgFileTypeMsgId    MsgFileType = 4
	MsgFileType_MsgFileTypeLoadBoot MsgFileType = 5
)

var MsgFileType_name = map[int32]string{
	0: "MsgFileTypeNil",
	1: "MsgFileTypeIdx",
	2: "MsgFileTypeData",
	3: "MsgFileTypeFinish",
	4: "MsgFileTypeMsgId",
	5: "MsgFileTypeLoadBoot",
}
var MsgFileType_value = map[string]int32{
	"MsgFileTypeNil":      0,
	"MsgFileTypeIdx":      1,
	"MsgFileTypeData":     2,
	"MsgFileTypeFinish":   3,
	"MsgFileTypeMsgId":    4,
	"MsgFileTypeLoadBoot": 5,
}

func (x MsgFileType) String() string {
	return proto.EnumName(MsgFileType_name, int32(x))
}
func (MsgFileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ha_5b08e5bd27bb5899, []int{0}
}

type Node struct {
	NodeGrp              string   `protobuf:"bytes,1,opt,name=node_grp,json=nodeGrp,proto3" json:"node_grp,omitempty"`
	IsMaster             bool     `protobuf:"varint,2,opt,name=is_master,json=isMaster,proto3" json:"is_master,omitempty"`
	MaxSyncedLogId       uint64   `protobuf:"varint,3,opt,name=max_synced_log_id,json=maxSyncedLogId,proto3" json:"max_synced_log_id,omitempty"`
	TermOfMaxSyncedLog   uint64   `protobuf:"varint,4,opt,name=term_of_max_synced_log,json=termOfMaxSyncedLog,proto3" json:"term_of_max_synced_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_ha_5b08e5bd27bb5899, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetNodeGrp() string {
	if m != nil {
		return m.NodeGrp
	}
	return ""
}

func (m *Node) GetIsMaster() bool {
	if m != nil {
		return m.IsMaster
	}
	return false
}

func (m *Node) GetMaxSyncedLogId() uint64 {
	if m != nil {
		return m.MaxSyncedLogId
	}
	return 0
}

func (m *Node) GetTermOfMaxSyncedLog() uint64 {
	if m != nil {
		return m.TermOfMaxSyncedLog
	}
	return 0
}

type SyncMsgFileLogItem struct {
	Topic                string      `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Subscriber           string      `protobuf:"bytes,2,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	FileBuf              []byte      `protobuf:"bytes,3,opt,name=file_buf,json=fileBuf,proto3" json:"file_buf,omitempty"`
	MsgFileType          MsgFileType `protobuf:"varint,4,opt,name=msg_file_type,json=msgFileType,proto3,enum=broker.MsgFileType" json:"msg_file_type,omitempty"`
	FileName             string      `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	CreatedAt            uint32      `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FileOffset           uint32      `protobuf:"varint,7,opt,name=file_offset,json=fileOffset,proto3" json:"file_offset,omitempty"`
	LogId                uint64      `protobuf:"varint,8,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	IsSyncFromMaster     bool        `protobuf:"varint,9,opt,name=is_sync_from_master,json=isSyncFromMaster,proto3" json:"is_sync_from_master,omitempty"`
	Term                 uint64      `protobuf:"varint,10,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SyncMsgFileLogItem) Reset()         { *m = SyncMsgFileLogItem{} }
func (m *SyncMsgFileLogItem) String() string { return proto.CompactTextString(m) }
func (*SyncMsgFileLogItem) ProtoMessage()    {}
func (*SyncMsgFileLogItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ha_5b08e5bd27bb5899, []int{1}
}
func (m *SyncMsgFileLogItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMsgFileLogItem.Unmarshal(m, b)
}
func (m *SyncMsgFileLogItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMsgFileLogItem.Marshal(b, m, deterministic)
}
func (dst *SyncMsgFileLogItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMsgFileLogItem.Merge(dst, src)
}
func (m *SyncMsgFileLogItem) XXX_Size() int {
	return xxx_messageInfo_SyncMsgFileLogItem.Size(m)
}
func (m *SyncMsgFileLogItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMsgFileLogItem.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMsgFileLogItem proto.InternalMessageInfo

func (m *SyncMsgFileLogItem) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SyncMsgFileLogItem) GetSubscriber() string {
	if m != nil {
		return m.Subscriber
	}
	return ""
}

func (m *SyncMsgFileLogItem) GetFileBuf() []byte {
	if m != nil {
		return m.FileBuf
	}
	return nil
}

func (m *SyncMsgFileLogItem) GetMsgFileType() MsgFileType {
	if m != nil {
		return m.MsgFileType
	}
	return MsgFileType_MsgFileTypeNil
}

func (m *SyncMsgFileLogItem) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *SyncMsgFileLogItem) GetCreatedAt() uint32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *SyncMsgFileLogItem) GetFileOffset() uint32 {
	if m != nil {
		return m.FileOffset
	}
	return 0
}

func (m *SyncMsgFileLogItem) GetLogId() uint64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *SyncMsgFileLogItem) GetIsSyncFromMaster() bool {
	if m != nil {
		return m.IsSyncFromMaster
	}
	return false
}

func (m *SyncMsgFileLogItem) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type SyncRemoteReplicaReq struct {
	LogItems             []*SyncMsgFileLogItem `protobuf:"bytes,1,rep,name=log_items,json=logItems,proto3" json:"log_items,omitempty"`
	LastSyncedLogId      uint64                `protobuf:"varint,2,opt,name=last_synced_log_id,json=lastSyncedLogId,proto3" json:"last_synced_log_id,omitempty"`
	TermOfLastSyncedLog  uint64                `protobuf:"varint,3,opt,name=term_of_last_synced_log,json=termOfLastSyncedLog,proto3" json:"term_of_last_synced_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SyncRemoteReplicaReq) Reset()         { *m = SyncRemoteReplicaReq{} }
func (m *SyncRemoteReplicaReq) String() string { return proto.CompactTextString(m) }
func (*SyncRemoteReplicaReq) ProtoMessage()    {}
func (*SyncRemoteReplicaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ha_5b08e5bd27bb5899, []int{2}
}
func (m *SyncRemoteReplicaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRemoteReplicaReq.Unmarshal(m, b)
}
func (m *SyncRemoteReplicaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRemoteReplicaReq.Marshal(b, m, deterministic)
}
func (dst *SyncRemoteReplicaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRemoteReplicaReq.Merge(dst, src)
}
func (m *SyncRemoteReplicaReq) XXX_Size() int {
	return xxx_messageInfo_SyncRemoteReplicaReq.Size(m)
}
func (m *SyncRemoteReplicaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRemoteReplicaReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRemoteReplicaReq proto.InternalMessageInfo

func (m *SyncRemoteReplicaReq) GetLogItems() []*SyncMsgFileLogItem {
	if m != nil {
		return m.LogItems
	}
	return nil
}

func (m *SyncRemoteReplicaReq) GetLastSyncedLogId() uint64 {
	if m != nil {
		return m.LastSyncedLogId
	}
	return 0
}

func (m *SyncRemoteReplicaReq) GetTermOfLastSyncedLog() uint64 {
	if m != nil {
		return m.TermOfLastSyncedLog
	}
	return 0
}

type SyncRemoteReplicaResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRemoteReplicaResp) Reset()         { *m = SyncRemoteReplicaResp{} }
func (m *SyncRemoteReplicaResp) String() string { return proto.CompactTextString(m) }
func (*SyncRemoteReplicaResp) ProtoMessage()    {}
func (*SyncRemoteReplicaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ha_5b08e5bd27bb5899, []int{3}
}
func (m *SyncRemoteReplicaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRemoteReplicaResp.Unmarshal(m, b)
}
func (m *SyncRemoteReplicaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRemoteReplicaResp.Marshal(b, m, deterministic)
}
func (dst *SyncRemoteReplicaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRemoteReplicaResp.Merge(dst, src)
}
func (m *SyncRemoteReplicaResp) XXX_Size() int {
	return xxx_messageInfo_SyncRemoteReplicaResp.Size(m)
}
func (m *SyncRemoteReplicaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRemoteReplicaResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRemoteReplicaResp proto.InternalMessageInfo

type PullRemoteReplicaReq struct {
	LastSyncedLogId      uint64   `protobuf:"varint,2,opt,name=last_synced_log_id,json=lastSyncedLogId,proto3" json:"last_synced_log_id,omitempty"`
	TermOfLastSyncedLog  uint64   `protobuf:"varint,3,opt,name=term_of_last_synced_log,json=termOfLastSyncedLog,proto3" json:"term_of_last_synced_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRemoteReplicaReq) Reset()         { *m = PullRemoteReplicaReq{} }
func (m *PullRemoteReplicaReq) String() string { return proto.CompactTextString(m) }
func (*PullRemoteReplicaReq) ProtoMessage()    {}
func (*PullRemoteReplicaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ha_5b08e5bd27bb5899, []int{4}
}
func (m *PullRemoteReplicaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRemoteReplicaReq.Unmarshal(m, b)
}
func (m *PullRemoteReplicaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRemoteReplicaReq.Marshal(b, m, deterministic)
}
func (dst *PullRemoteReplicaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRemoteReplicaReq.Merge(dst, src)
}
func (m *PullRemoteReplicaReq) XXX_Size() int {
	return xxx_messageInfo_PullRemoteReplicaReq.Size(m)
}
func (m *PullRemoteReplicaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRemoteReplicaReq.DiscardUnknown(m)
}

var xxx_messageInfo_PullRemoteReplicaReq proto.InternalMessageInfo

func (m *PullRemoteReplicaReq) GetLastSyncedLogId() uint64 {
	if m != nil {
		return m.LastSyncedLogId
	}
	return 0
}

func (m *PullRemoteReplicaReq) GetTermOfLastSyncedLog() uint64 {
	if m != nil {
		return m.TermOfLastSyncedLog
	}
	return 0
}

type PullRemoteReplicaResp struct {
	LogItems             []*SyncMsgFileLogItem `protobuf:"bytes,1,rep,name=log_items,json=logItems,proto3" json:"log_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PullRemoteReplicaResp) Reset()         { *m = PullRemoteReplicaResp{} }
func (m *PullRemoteReplicaResp) String() string { return proto.CompactTextString(m) }
func (*PullRemoteReplicaResp) ProtoMessage()    {}
func (*PullRemoteReplicaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ha_5b08e5bd27bb5899, []int{5}
}
func (m *PullRemoteReplicaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRemoteReplicaResp.Unmarshal(m, b)
}
func (m *PullRemoteReplicaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRemoteReplicaResp.Marshal(b, m, deterministic)
}
func (dst *PullRemoteReplicaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRemoteReplicaResp.Merge(dst, src)
}
func (m *PullRemoteReplicaResp) XXX_Size() int {
	return xxx_messageInfo_PullRemoteReplicaResp.Size(m)
}
func (m *PullRemoteReplicaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRemoteReplicaResp.DiscardUnknown(m)
}

var xxx_messageInfo_PullRemoteReplicaResp proto.InternalMessageInfo

func (m *PullRemoteReplicaResp) GetLogItems() []*SyncMsgFileLogItem {
	if m != nil {
		return m.LogItems
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "broker.Node")
	proto.RegisterType((*SyncMsgFileLogItem)(nil), "broker.SyncMsgFileLogItem")
	proto.RegisterType((*SyncRemoteReplicaReq)(nil), "broker.SyncRemoteReplicaReq")
	proto.RegisterType((*SyncRemoteReplicaResp)(nil), "broker.SyncRemoteReplicaResp")
	proto.RegisterType((*PullRemoteReplicaReq)(nil), "broker.PullRemoteReplicaReq")
	proto.RegisterType((*PullRemoteReplicaResp)(nil), "broker.PullRemoteReplicaResp")
	proto.RegisterEnum("broker.MsgFileType", MsgFileType_name, MsgFileType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HAClient is the client API for HA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HAClient interface {
	SyncRemoteReplica(ctx context.Context, in *SyncRemoteReplicaReq, opts ...grpc.CallOption) (*SyncRemoteReplicaResp, error)
	PullRemoteReplica(ctx context.Context, in *PullRemoteReplicaReq, opts ...grpc.CallOption) (*PullRemoteReplicaResp, error)
}

type hAClient struct {
	cc *grpc.ClientConn
}

func NewHAClient(cc *grpc.ClientConn) HAClient {
	return &hAClient{cc}
}

func (c *hAClient) SyncRemoteReplica(ctx context.Context, in *SyncRemoteReplicaReq, opts ...grpc.CallOption) (*SyncRemoteReplicaResp, error) {
	out := new(SyncRemoteReplicaResp)
	err := c.cc.Invoke(ctx, "/broker.HA/SyncRemoteReplica", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hAClient) PullRemoteReplica(ctx context.Context, in *PullRemoteReplicaReq, opts ...grpc.CallOption) (*PullRemoteReplicaResp, error) {
	out := new(PullRemoteReplicaResp)
	err := c.cc.Invoke(ctx, "/broker.HA/PullRemoteReplica", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HAServer is the server API for HA service.
type HAServer interface {
	SyncRemoteReplica(context.Context, *SyncRemoteReplicaReq) (*SyncRemoteReplicaResp, error)
	PullRemoteReplica(context.Context, *PullRemoteReplicaReq) (*PullRemoteReplicaResp, error)
}

func RegisterHAServer(s *grpc.Server, srv HAServer) {
	s.RegisterService(&_HA_serviceDesc, srv)
}

func _HA_SyncRemoteReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRemoteReplicaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAServer).SyncRemoteReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/broker.HA/SyncRemoteReplica",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAServer).SyncRemoteReplica(ctx, req.(*SyncRemoteReplicaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HA_PullRemoteReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRemoteReplicaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAServer).PullRemoteReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/broker.HA/PullRemoteReplica",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAServer).PullRemoteReplica(ctx, req.(*PullRemoteReplicaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "broker.HA",
	HandlerType: (*HAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncRemoteReplica",
			Handler:    _HA_SyncRemoteReplica_Handler,
		},
		{
			MethodName: "PullRemoteReplica",
			Handler:    _HA_PullRemoteReplica_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ha.proto",
}

func init() { proto.RegisterFile("pkg/proto/ha.proto", fileDescriptor_ha_5b08e5bd27bb5899) }

var fileDescriptor_ha_5b08e5bd27bb5899 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x71, 0x9a, 0xa4, 0xc9, 0x84, 0xb6, 0xee, 0x24, 0xa1, 0xa6, 0x50, 0x88, 0x72, 0x0a,
	0x45, 0x24, 0x52, 0x5a, 0x54, 0xf5, 0xd8, 0x0a, 0x15, 0x2a, 0x35, 0x6d, 0x65, 0x38, 0x71, 0xb1,
	0xd6, 0xf6, 0xda, 0x59, 0xd5, 0x9b, 0x75, 0xbd, 0x1b, 0xa9, 0x79, 0x0b, 0x5e, 0x80, 0x3b, 0x67,
	0xde, 0x85, 0xf7, 0x41, 0xbb, 0x71, 0x15, 0x93, 0x44, 0x1c, 0x38, 0x70, 0xdb, 0xf9, 0xcf, 0xce,
	0xc7, 0xfe, 0x66, 0xb4, 0x80, 0xe9, 0x5d, 0x3c, 0x48, 0x33, 0xa1, 0xc4, 0x60, 0x4c, 0xfa, 0xe6,
	0x80, 0x55, 0x3f, 0x13, 0x77, 0x34, 0xeb, 0x7e, 0xb7, 0xa0, 0x7c, 0x2d, 0x42, 0x8a, 0xcf, 0xa1,
	0x36, 0x11, 0x21, 0xf5, 0xe2, 0x2c, 0x75, 0xac, 0x8e, 0xd5, 0xab, 0xbb, 0x9b, 0xda, 0xfe, 0x98,
	0xa5, 0xf8, 0x02, 0xea, 0x4c, 0x7a, 0x9c, 0x48, 0x45, 0x33, 0xa7, 0xd4, 0xb1, 0x7a, 0x35, 0xb7,
	0xc6, 0xe4, 0xc8, 0xd8, 0xf8, 0x06, 0x76, 0x39, 0x79, 0xf0, 0xe4, 0x6c, 0x12, 0xd0, 0xd0, 0x4b,
	0x44, 0xec, 0xb1, 0xd0, 0xd9, 0xe8, 0x58, 0xbd, 0xb2, 0xbb, 0xcd, 0xc9, 0xc3, 0x67, 0xa3, 0x5f,
	0x89, 0xf8, 0x32, 0xc4, 0x21, 0x3c, 0x53, 0x34, 0xe3, 0x9e, 0x88, 0xbc, 0x3f, 0x43, 0x9c, 0xb2,
	0xb9, 0x8f, 0xda, 0x7b, 0x13, 0x8d, 0x0a, 0x51, 0xdd, 0x5f, 0x25, 0x40, 0x6d, 0x8d, 0x64, 0x7c,
	0xc1, 0x12, 0xaa, 0x13, 0x29, 0xca, 0xb1, 0x05, 0x15, 0x25, 0x52, 0x16, 0xe4, 0xad, 0xce, 0x0d,
	0x7c, 0x05, 0x20, 0xa7, 0xbe, 0x0c, 0x32, 0xe6, 0xe7, 0x9d, 0xd6, 0xdd, 0x82, 0xa2, 0xdf, 0x18,
	0xb1, 0x84, 0x7a, 0xfe, 0x34, 0x32, 0x2d, 0x3e, 0x75, 0x37, 0xb5, 0x7d, 0x3e, 0x8d, 0xf0, 0x04,
	0xb6, 0xb8, 0x8c, 0x3d, 0xe3, 0x56, 0xb3, 0x94, 0x9a, 0x96, 0xb6, 0x87, 0xcd, 0xfe, 0x9c, 0x53,
	0x3f, 0xaf, 0xff, 0x65, 0x96, 0x52, 0xb7, 0xc1, 0x17, 0x86, 0x86, 0x63, 0x82, 0x26, 0x84, 0x53,
	0xa7, 0x62, 0x4a, 0x9a, 0x22, 0xd7, 0x84, 0x53, 0x3c, 0x00, 0x08, 0x32, 0x4a, 0x14, 0x0d, 0x3d,
	0xa2, 0x9c, 0x6a, 0xc7, 0xea, 0x6d, 0xb9, 0xf5, 0x5c, 0x39, 0x53, 0xf8, 0x1a, 0x1a, 0x26, 0x56,
	0x44, 0x91, 0xa4, 0xca, 0xd9, 0x34, 0x7e, 0xd0, 0xd2, 0x8d, 0x51, 0xb0, 0x0d, 0xd5, 0x9c, 0x68,
	0xcd, 0x10, 0xaa, 0x24, 0x06, 0xe4, 0x3b, 0x68, 0x32, 0x69, 0xf8, 0x79, 0x51, 0x26, 0xf8, 0xe3,
	0x68, 0xea, 0x66, 0x34, 0x36, 0x93, 0x1a, 0xd8, 0x45, 0x26, 0x78, 0x3e, 0x22, 0x84, 0xb2, 0x26,
	0xeb, 0x80, 0xc9, 0x61, 0xce, 0xdd, 0x9f, 0x16, 0xb4, 0xf4, 0x35, 0x97, 0x72, 0xa1, 0xa8, 0x4b,
	0xd3, 0x84, 0x05, 0xc4, 0xa5, 0xf7, 0x78, 0x02, 0x75, 0x53, 0x52, 0x51, 0x2e, 0x1d, 0xab, 0xb3,
	0xd1, 0x6b, 0x0c, 0xf7, 0x1f, 0x21, 0xac, 0x0e, 0xc2, 0xad, 0x25, 0xf3, 0x83, 0xc4, 0xb7, 0x80,
	0x09, 0x91, 0x6a, 0x69, 0x13, 0x4a, 0xa6, 0xe6, 0x8e, 0xf6, 0x14, 0x57, 0xe1, 0x18, 0xf6, 0x1e,
	0x57, 0x61, 0x29, 0x28, 0xdf, 0x9d, 0xe6, 0x7c, 0x17, 0xae, 0x8a, 0x71, 0xdd, 0x3d, 0x68, 0xaf,
	0xe9, 0x59, 0xa6, 0xdd, 0x19, 0xb4, 0x6e, 0xa7, 0x49, 0xb2, 0xf2, 0x98, 0xff, 0xd0, 0xd3, 0x2d,
	0xb4, 0xd7, 0x94, 0x96, 0xe9, 0x3f, 0x83, 0x3c, 0xfc, 0x66, 0x41, 0xa3, 0xb0, 0x6e, 0x88, 0xb0,
	0x5d, 0x30, 0xaf, 0x59, 0x62, 0x3f, 0x59, 0xd2, 0x2e, 0xc3, 0x07, 0xdb, 0xc2, 0x26, 0xec, 0x14,
	0xb4, 0x0f, 0x44, 0x11, 0xbb, 0x84, 0x6d, 0xd8, 0x2d, 0x88, 0x17, 0x6c, 0xc2, 0xe4, 0xd8, 0xde,
	0xc0, 0x16, 0xd8, 0x05, 0x79, 0x24, 0xe3, 0xcb, 0xd0, 0x2e, 0xe3, 0x1e, 0x34, 0x0b, 0xea, 0x95,
	0x20, 0xe1, 0xb9, 0x10, 0xca, 0xae, 0x0c, 0x7f, 0x58, 0x50, 0xfa, 0x74, 0x86, 0xb7, 0xb0, 0xbb,
	0xc2, 0x1f, 0x5f, 0x16, 0x1f, 0xb5, 0x3c, 0x81, 0xfd, 0x83, 0xbf, 0x78, 0x65, 0xaa, 0x33, 0xae,
	0xd0, 0x5b, 0x64, 0x5c, 0x37, 0xd3, 0x45, 0xc6, 0xb5, 0xd8, 0xcf, 0x0f, 0xbf, 0xf6, 0x62, 0xa6,
	0xc6, 0x53, 0xbf, 0x1f, 0x08, 0x3e, 0x38, 0x3d, 0x7d, 0x7f, 0x7a, 0x74, 0x74, 0x7c, 0x7c, 0x32,
	0xf0, 0xa7, 0xc1, 0x1d, 0x55, 0xfc, 0x7e, 0xa0, 0x3f, 0xc3, 0x2c, 0x0d, 0x06, 0x63, 0xe2, 0x57,
	0xcd, 0x5f, 0x78, 0xf4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xe6, 0x96, 0xff, 0x21, 0x05, 0x00,
	0x00,
}
